package com.ebi.assessment.person.persistance;

import io.swagger.annotations.ApiModelProperty;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import java.io.Serializable;

@Entity
@Builder(builderClassName = "Builder", setterPrefix = "with", toBuilder = true)
@Getter
@ToString
@EqualsAndHashCode
public class PersonEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty("Resource Id - Autogenerated")
    private Integer id;
    @ApiModelProperty("First name")
    private String firstName;
    @ApiModelProperty("Last name")
    private String lastName;
    @ApiModelProperty("Age")
    private Integer age;
    @ApiModelProperty("Favorite Color")
    private String favoriteColor;

    protected PersonEntity() {
    }

    public PersonEntity(final Integer id,
                        final String firstName,
                        final String lastName,
                        final Integer age,
                        final String favoriteColor) {

        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.age = age;
        this.favoriteColor = favoriteColor;
    }
}
